image: node:4.4.2

cache:
  paths:
  - node_modules/

before_script:
  - npm set progress=false
  - npm install --silent

test:
  script:
  - npm run test
  only:
  - development

staging:
  type: deploy
  script:
  - npm run build
  - apt-get install -yqq ruby ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_STAGING_NAME --api-key=$HEROKU_STAGING_API_KEY
  only:
  - development
