image: node:4.4.2

cache:
  paths:
  - node_modules/

test:
  script:
  - npm install
  - npm run test

staging:
  type: deploy
  script:
  - npm install
  - npm run build
  - gem install dpl
  - dpl --provider=heroku --app=miracle-fontend-dev --api-key=$HEROKU_STAGING_API_KEY
  only:
    - development
