image: node:4.4.2

cache:
  paths:
  - node_modules/

before_script:
  - npm -g install npm --silent
  - npm set progress=false
  - npm install --silent

test:
  script:
  - npm run test

staging:
  type: deploy
  script:
  - npm run build
  - SLUG=$(echo ${CI_BUILD_REF_NAME} | sed 's/[^a-zA-Z0-9\-_]/-/g ; s/-\+/-/g')
  - node_modules/.bin/surge build $HEROKU_STAGING_NAME-${SLUG}.surge.sh
  except:
  - master
